from html.parser import HTMLParser

from svfuzzer import SVFuzzer


def feed(data):
    p = HTMLParser()
    p.feed(data)


seeds = [
    "<a>",
    "<a/>",
    "<address>",
    "<address/>",
    "<area>",
    "<area/>",
    "<article>",
    "<article/>",
    "<aside>",
    "<aside/>",
    "<audio>",
    "<audio/>",
    "<b>",
    "<b/>",
    "<base>",
    "<base/>",
    "<bdi>",
    "<bdi/>",
    "<bdo>",
    "<bdo/>",
    "<blockquote>",
    "<blockquote/>",
    "<body>",
    "<body/>",
    "<br>",
    "<br/>",
    "<button>",
    "<button/>",
    "<canvas>",
    "<canvas/>",
    "<caption>",
    "<caption/>",
    "<cite>",
    "<cite/>",
    "<code>",
    "<code/>",
    "<col>",
    "<col/>",
    "<colgroup>",
    "<colgroup/>",
    "<data>",
    "<data/>",
    "<datalist>",
    "<datalist/>",
    "<dd>",
    "<dd/>",
    "<del>",
    "<del/>",
    "<details>",
    "<details/>",
    "<dfn>",
    "<dfn/>",
    "<dialog>",
    "<dialog/>",
    "<div>",
    "<div/>",
    "<dl>",
    "<dl/>",
    "<dt>",
    "<dt/>",
    "<em>",
    "<em/>",
    "<embed>",
    "<embed/>",
    "<fieldset>",
    "<fieldset/>",
    "<figcaption>",
    "<figcaption/>",
    "<figure>",
    "<figure/>",
    "<footer>",
    "<footer/>",
    "<form>",
    "<form/>",
    "<h1>",
    "<h1/>",
    "<h2>",
    "<h2/>",
    "<h3>",
    "<h3/>",
    "<h4>",
    "<h4/>",
    "<h5>",
    "<h5/>",
    "<h6>",
    "<h6/>",
    "<head>",
    "<head/>",
    "<header>",
    "<header/>",
    "<hgroup>",
    "<hgroup/>",
    "<hr>",
    "<hr/>",
    "<html>",
    "<html/>",
    "<i>",
    "<i/>",
    "<iframe>",
    "<iframe/>",
    "<img>",
    "<img/>",
    "<input>",
    "<input/>",
    "<ins>",
    "<ins/>",
    "<kbd>",
    "<kbd/>",
    "<label>",
    "<label/>",
    "<legend>",
    "<legend/>",
    "<li>",
    "<li/>",
    "<link>",
    "<link/>",
    "<main>",
    "<main/>",
    "<map>",
    "<map/>",
    "<mark>",
    "<mark/>",
    "<math>",
    "<math/>",
    "<menu>",
    "<menu/>",
    "<menuitem>",
    "<menuitem/>",
    "<meta>",
    "<meta/>",
    "<meter>",
    "<meter/>",
    "<nav>",
    "<nav/>",
    "<noscript>",
    "<noscript/>",
    "<object>",
    "<object/>",
    "<ol>",
    "<ol/>",
    "<optgroup>",
    "<optgroup/>",
    "<option>",
    "<option/>",
    "<output>",
    "<output/>",
    "<p>",
    "<p/>",
    "<param>",
    "<param/>",
    "<picture>",
    "<picture/>",
    "<pre>",
    "<pre/>",
    "<progress>",
    "<progress/>",
    "<q>",
    "<q/>",
    "<rb>",
    "<rb/>",
    "<rp>",
    "<rp/>",
    "<rt>",
    "<rt/>",
    "<rtc>",
    "<rtc/>",
    "<ruby>",
    "<ruby/>",
    "<s>",
    "<s/>",
    "<samp>",
    "<samp/>",
    "<script>",
    "<script/>",
    "<search>",
    "<search/>",
    "<section>",
    "<section/>",
    "<select>",
    "<select/>",
    "<slot>",
    "<slot/>",
    "<small>",
    "<small/>",
    "<source>",
    "<source/>",
    "<span>",
    "<span/>",
    "<strong>",
    "<strong/>",
    "<style>",
    "<style/>",
    "<sub>",
    "<sub/>",
    "<summary>",
    "<summary/>",
    "<sup>",
    "<sup/>",
    "<svg>",
    "<svg/>",
    "<table>",
    "<table/>",
    "<tbody>",
    "<tbody/>",
    "<td>",
    "<td/>",
    "<template>",
    "<template/>",
    "<textarea>",
    "<textarea/>",
    "<tfoot>",
    "<tfoot/>",
    "<th>",
    "<th/>",
    "<thead>",
    "<thead/>",
    "<time>",
    "<time/>",
    "<title>",
    "<title/>",
    "<tr>",
    "<tr/>",
    "<track>",
    "<track/>",
    "<u>",
    "<u/>",
    "<ul>",
    "<ul/>",
    "<var>",
    "<var/>",
    "<video>",
    "<video/>",
    "<wbr>"
    "<wbr/>"
]

seeds2 = ['<a><a/>', '<address><address/>', '<area><area/>', '<article><article/>', '<aside><aside/>',
          '<audio><audio/>',
          '<b><b/>', '<base><base/>', '<bdi><bdi/>', '<bdo><bdo/>', '<blockquote><blockquote/>', '<body><body/>',
          '<br><br/>', '<button><button/>', '<canvas><canvas/>', '<caption><caption/>', '<cite><cite/>',
          '<code><code/>',
          '<col><col/>', '<colgroup><colgroup/>', '<data><data/>', '<datalist><datalist/>', '<dd><dd/>', '<del><del/>',
          '<details><details/>', '<dfn><dfn/>', '<dialog><dialog/>', '<div><div/>', '<dl><dl/>', '<dt><dt/>',
          '<em><em/>',
          '<embed><embed/>', '<fieldset><fieldset/>', '<figcaption><figcaption/>', '<figure><figure/>',
          '<footer><footer/>',
          '<form><form/>', '<h1><h1/>', '<h2><h2/>', '<h3><h3/>', '<h4><h4/>', '<h5><h5/>', '<h6><h6/>',
          '<head><head/>',
          '<header><header/>', '<hgroup><hgroup/>', '<hr><hr/>', '<html><html/>', '<i><i/>', '<iframe><iframe/>',
          '<img><img/>', '<input><input/>', '<ins><ins/>', '<kbd><kbd/>', '<label><label/>', '<legend><legend/>',
          '<li><li/>', '<link><link/>', '<main><main/>', '<map><map/>', '<mark><mark/>', '<math><math/>',
          '<menu><menu/>',
          '<menuitem><menuitem/>', '<meta><meta/>', '<meter><meter/>', '<nav><nav/>', '<noscript><noscript/>',
          '<object><object/>', '<ol><ol/>', '<optgroup><optgroup/>', '<option><option/>', '<output><output/>',
          '<p><p/>',
          '<param><param/>', '<picture><picture/>', '<pre><pre/>', '<progress><progress/>', '<q><q/>', '<rb><rb/>',
          '<rp><rp/>', '<rt><rt/>', '<rtc><rtc/>', '<ruby><ruby/>', '<s><s/>', '<samp><samp/>', '<script><script/>',
          '<search><search/>', '<section><section/>', '<select><select/>', '<slot><slot/>', '<small><small/>',
          '<source><source/>', '<span><span/>', '<strong><strong/>', '<style><style/>', '<sub><sub/>',
          '<summary><summary/>',
          '<sup><sup/>', '<svg><svg/>', '<table><table/>', '<tbody><tbody/>', '<td><td/>', '<template><template/>',
          '<textarea><textarea/>', '<tfoot><tfoot/>', '<th><th/>', '<thead><thead/>', '<time><time/>',
          '<title><title/>',
          '<tr><tr/>', '<track><track/>', '<u><u/>', '<ul><ul/>', '<var><var/>', '<video><video/>', '<wbr><wbr/>']

s = SVFuzzer(0, 15000, seeds + seeds2, "html/parser.py", feed)

s.runs()
